---
- hosts: all
  
  tasks:
  - name: "Create upper level directory"
    file:
      path: /var/tmp/{{ inventory }}
      state: directory
      mode: 0755
  - name: "Create example config file"
    file:
      path: /var/tmp/{{ inventory }}/config_file
      state: touch
      mode: 0755
  
  - name: "Set variables in the config file"
    lineinfile:
      path: /var/tmp/top-level/config_file
      regexp: '^DNSservers='
      line: "DNSservers={{ dns_server }}"
      
  - name: "Set variables in the config file 2"
    lineinfile:
      path: /var/tmp/top-level/config_file
      regexp: '^location='
      line: "location={{ location }}"
